language: go

os:
  - linux
  - osx

go:
  - 1.x

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl && brew link openssl --force; fi;

script:
    - ./tests/test.sh
