site_name: fakit - FASTA kit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Benchmark: benchmark.md
- Extension: extension.md
theme: mkdocs

repo_url: https://github.com/shenwei356/fakit
site_description: fakit - Practical FASTA kit
site_author: shenwei356
google_analytics: ['UA-28948626-3', 'blog.shenwei.me/fakit']
