site_name: SeqKit - Ultrafast FASTA/Q kit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Tutorial: tutorial.md
- Benchmark: benchmark.md
- YanLi Lab: yanlilab.md
theme: mkdocs

repo_url: https://github.com/shenwei356/seqkit
site_description: SeqKit - a cross-platform and ultrafast toolkit for FASTA/Q file manipulation
site_author: Wei Shen
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/seqkit']
