site_name: faskit - FASTA/Q kit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Tutorial: tutorial.md
- Benchmark: benchmark.md
theme: mkdocs

repo_url: https://github.com/shenwei356/faskit
site_description: faskit - Practical FASTA kit
site_author: shenwei356
google_analytics: ['UA-28948626-3', 'blog.shenwei.me/faskit']
