site_name: SeqKit - Ultrafast FASTA/Q kit
pages:
- Home: index.md
- Download: download.md
- Documents:
    - Usage: usage.md
    - FAQ: faq.md
    - Tutorial: tutorial.md
    - Benchmark: benchmark.md
    - Notes: note.md
- Links:
    - More tools: bioinf.md
    - YanLi Lab: yanlilab.md
theme: cinder

# cluster
# tamerdocs
# cinder
# unidata
# yeti

repo_url: https://github.com/shenwei356/seqkit
site_description: SeqKit - a cross-platform and ultrafast toolkit for FASTA/Q file manipulation
site_author: Wei Shen
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/seqkit']
